### ISSUE TITLE
Not compatible with Zeitwerk loader in Rails 6+ ?

### ISSUE THREAD

**Issue by ksouthworth** [htmlcsstoimage/ruby-client#3]
I'm trying to use this gem inside a Rails 6 project, but I'm getting lots of errors just trying to reference the library.

Errors like:
`uninitialized constant HTMLCSSToImage`

It works in `Rails.env.development` environment with a
`require "HTMLCSSToImage"`
at the top of my file, but that breaks when I deploy to a staging or production Rails environment (likely due to some incompabibility with the Zeitwek loader?)

**Comment by mscoutermarsh** [comment]
Sorry for the delay, missed this notification!

Did you try with the require in all lowercase?

```Ruby
require "htmlcsstoimage"
```

I just tried it with a Rails 6 app (Zeitwerk enabled) and it worked in both development and production mode.

**Comment by mscoutermarsh** [comment]
If that doesn't work could you share your specific Rails version? I'll try to recreate that way. Thanks!
